const NS='http://www.w3.org/2000/svg', colors={Portfolio:'#142b43',SPY:'#326c9e',IEF:'#6d9d99',HYG:'#9c738b',GLD:'#b28c3e'}, assets=['SPY','IEF','HYG','GLD'];
const pct=v=>(v*100).toFixed(2)+'%', date=v=>new Date(v).toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'});
function el(tag,attrs={},text){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e}
function svg(id,w=600,h=280){const c=document.getElementById(id);c.replaceChildren();const s=el('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':id+' interactive chart'});c.append(s);return s}
function txt(s,x,y,t,attrs={}){s.append(el('text',{x,y,...attrs},t))}
function line(s,x1,y1,x2,y2,attrs={}){s.append(el('line',{x1,y1,x2,y2,stroke:'#dde5eb',...attrs}))}
function interactive(e,html){e.classList.add('datum');e.setAttribute('tabindex','0');e.setAttribute('role','button');e.setAttribute('aria-label',html.replace(/<[^>]*>/g,' '));const tip=document.getElementById('tooltip');function show(ev){tip.innerHTML=html;tip.style.display='block';const r=e.getBoundingClientRect();const x=ev.clientX||r.x,y=ev.clientY||r.y;tip.style.left=Math.max(8,Math.min(innerWidth-300,x+12))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-tip.offsetHeight-10,y+12))+'px'}e.addEventListener('pointerenter',show);e.addEventListener('pointermove',show);e.addEventListener('click',show);e.addEventListener('focus',show);e.addEventListener('pointerleave',()=>tip.style.display='none');e.addEventListener('blur',()=>tip.style.display='none');e.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' ')show(ev)});return e}
function rates(metric='return'){const s=svg('rates'),g=regimes.filter(r=>r.dimension==='rates'&&r.regime!=='Unchanged');const key=metric==='return'?'average_monthly_return':'annualized_volatility',min=metric==='return'?-.005:0,max=metric==='return'?.025:.1,y=v=>220-(v-min)/(max-min)*185;[min,0,(max+min)/2,max].forEach(v=>{line(s,65,y(v),575,y(v));txt(s,55,y(v)+5,pct(v),{'text-anchor':'end'})});g.forEach((r,i)=>{const x=150+i*250,v=r[key];s.append(interactive(el('rect',{x,y:Math.min(y(0),y(v)),width:100,height:Math.max(2,Math.abs(y(v)-y(0))),fill:r.regime==='Rising'?'#9c738b':'#326c9e'}),`<b>${r.regime} yields · ${r.observations} months</b><br>Average return: ${pct(r.average_monthly_return)}<br>Annualized volatility: ${pct(r.annualized_volatility)}`));txt(s,x+50,250,r.regime,{'text-anchor':'middle'});txt(s,x+50,y(v)+(v<0?20:-10),pct(v),{'text-anchor':'middle',fill:'#142b43'})})}
function heat(dim='rates'){const s=svg('assets'),g=regimes.filter(r=>r.dimension===dim&&!['Missing','Unchanged'].includes(r.regime));assets.forEach((a,i)=>txt(s,205+i*100,40,a,{'text-anchor':'middle'}));g.forEach((r,j)=>{txt(s,140,102+j*86,`${r.regime} (${r.observations})`,{'text-anchor':'end'});assets.forEach((a,i)=>{let v=r[a+'_average_monthly_return'];let alpha=Math.min(.9,.15+Math.abs(v)*16);let color=v<0?`rgba(156,85,102,${alpha})`:`rgba(50,108,158,${alpha})`;let rect=el('rect',{x:160+i*100,y:60+j*86,width:90,height:70,fill:color});s.append(interactive(rect,`<b>${a} · ${r.regime} ${dim}</b><br>Average monthly return: ${pct(v)}<br>${r.observations} observations`));txt(s,205+i*100,102+j*86,pct(v),{'text-anchor':'middle','pointer-events':'none',style:'fill:#142b43'})})});txt(s,160,260,'Blue: positive return · red: negative return')}
const worstRows=[...monthly].sort((a,b)=>a.portfolio_return-b.portfolio_return).slice(0,10);let visible=new Set(['Portfolio',...assets]);
function worst(){const s=svg('worst',600,380),min=-.14,max=.08,x=v=>100+(v-min)/(max-min)*475;[-.12,-.08,-.04,0,.04,.08].forEach(v=>{line(s,x(v),10,x(v),342);txt(s,x(v),368,(v*100).toFixed(0)+'%',{'text-anchor':'middle'})});worstRows.forEach((r,j)=>{txt(s,90,27+j*32,date(r.month_end),{'text-anchor':'end',style:'font-size:12px'});[...visible].forEach((a,k)=>{const v=a==='Portfolio'?r.portfolio_return:r[a+'_return'];s.append(interactive(el('rect',{x:Math.min(x(0),x(v)),y:12+j*32+k*5,width:Math.max(1,Math.abs(x(v)-x(0))),height:4.5,fill:colors[a]}),`<b>${date(r.month_end)} · ${a}</b><br>Return: ${pct(v)}<br>Portfolio: ${pct(r.portfolio_return)}<br>VIX: ${r.VIX.toFixed(2)}<br>${r.rates_regime} yields / ${r.credit_regime} spreads`))})})}
function correlation(){const s=svg('correlation',600,380),x=i=>55+i/90*525,y=v=>25+(1-v)/2*280;[-1,-.5,0,.5,1].forEach(v=>{line(s,55,y(v),580,y(v));txt(s,45,y(v)+5,v.toFixed(1),{'text-anchor':'end'})});line(s,55,y(.7202885245),580,y(.7202885245),{stroke:'#9c738b','stroke-dasharray':'6 5'});txt(s,580,y(.7202885245)-8,'High threshold 0.7203',{'text-anchor':'end',style:'font-size:12px'});let path='';monthly.forEach((r,i)=>{if(r.corr!==null)path+=(path?'L':'M')+x(i)+' '+y(r.corr)+' ';if(r.joint)line(s,x(i),315,x(i),327,{stroke:'#b55764','stroke-width':3})});s.append(el('path',{d:path,fill:'none',stroke:'#326c9e','stroke-width':2.5}));monthly.forEach((r,i)=>{if(r.corr!==null)s.append(interactive(el('circle',{cx:x(i),cy:y(r.corr),r:5,fill:r.corr>.7202885245?'#9c738b':'#326c9e','fill-opacity':.25}),`<b>${date(r.month_end)}</b><br>12-month correlation: ${r.corr.toFixed(4)}<br>Above threshold: ${r.corr>.7202885245?'Yes':'No'}<br>SPY: ${pct(r.SPY_return)} / IEF: ${pct(r.IEF_return)}<br>Joint loss: ${r.joint?'Yes':'No'}`))});[0,24,48,72,90].forEach(i=>txt(s,x(i),355,date(monthly[i].month_end),{'text-anchor':i===0?'start':i===90?'end':'middle',style:'font-size:12px'}))}
document.querySelectorAll('#metric button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#metric button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('ratecaption').textContent=b.dataset.value==='return'?'Average monthly portfolio return (%)':'Annualized portfolio volatility (%)';rates(b.dataset.value)});document.getElementById('dimension').onchange=e=>heat(e.target.value);['Portfolio',...assets].forEach(a=>{let b=document.createElement('button');b.textContent=a;b.style.borderBottom='3px solid '+colors[a];b.setAttribute('aria-pressed','true');b.onclick=()=>{visible.has(a)?visible.delete(a):visible.add(a);b.setAttribute('aria-pressed',String(visible.has(a)));worst()};document.getElementById('legend').append(b)});rates();heat();worst();correlation();
